#!/bin/bash
./install_linux/bin/3DVisualizer -palette /gpfs/data/dhl/gfx/VisualizationData/Volumes/Medical/TissueScaffold/FiberAndBundle.pal -class ImageStack /gpfs/data/dhl/gfx/VisualizationData/Volumes/Medical/TissueScaffold/tif.stack
