#!/bin/bash
./install_linux/bin/MeshViewer /gpfs/data/dhl/gfx/VisualizationData/Biological/Gut/g01.obj /gpfs/data/dhl/gfx/VisualizationData/Biological/Gut/g02.obj /gpfs/data/dhl/gfx/VisualizationData/Biological/Gut/g03.obj
