#!/bin/bash
./install_linux/bin/MeshViewer /gpfs/data/dhl/gfx/VisualizationData/Surfaces/Biological/PterostichusTrachea/Pterostichus2-1.obj -vislet SceneGraphViewer /gpfs/data/dhl/gfx/VisualizationData/Elements/VirtualWalls/FOR90.vrml
