#!/bin/bash
rm ../install_linux/etc/Vrui-3.1/Vrui.cfg
cp ../install_linux/etc/Vrui-3.1/Vrui_Stereo.cfg ../install_linux/etc/Vrui-3.1/Vrui.cfg
../install_linux/bin/MeshViewer ../Objects/PlatynusTrachea/*.obj -vislet SceneGraphViewer ../Walls/FOR270.vrml
