#!/bin/bash
rm ../install_linux/etc/Vrui-3.1/Vrui.cfg
cp ../install_linux/etc/Vrui-3.1/Vrui_Mono.cfg ../install_linux/etc/Vrui-3.1/Vrui.cfg
../install_linux/bin/MeshViewer ../Objects/Pterostichus2-1.obj -vislet SceneGraphViewer ../Walls/FOR90.vrml
